name: komando_swimming_club
description: "Project for Komando Swimming Club"
publish_to: "none"
version: 1.1.1

environment:
  sdk: ^3.6.1

dependencies:
  animate_do: ^3.3.6
  animated_splash_screen: ^1.3.0
  flex_color_scheme: ^8.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  page_transition: ^2.2.1
  provider: ^6.1.2
  sizer: ^3.0.5
  sqflite: ^2.4.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
